version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: babycare-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: babycare
      POSTGRES_PASSWORD: babycare
      POSTGRES_DB: babycare
    ports:
      - '5432:5432'
    volumes:
      - babycare_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: babycare-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    volumes:
      - babycare_redis_data:/data

volumes:
  babycare_postgres_data:
  babycare_redis_data:
